version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=myAdmin
      - MYSQL_ROOT_PASSWORD=enter.2021
    ports:
      - '3306:3306'

  ayrotek-backend-challange:
    image: fatimeyukkaldiran/ayrotek-backend-challange:latest
    container_name: ayrotek-backend-challange
    ports:
      - "8080:8080"

  tax-calculator-service:
    image: fatimeyukkaldiran/tax-calculator-service:latest
    container_name: :tax-calculator-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
volumes:
  data: {}

networks:
  default:
    name: mongodb_network